name: manual_build

on: 
    workflow_dispatch:
    push:
      branches: Housekeeping

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            ref: 'Housekeeping'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE
        
      - name: Restore Packages
        run: nuget restore GeospatialEngineeringBIM.sln
        
      - name: Build Solution
        run: msbuild.exe GeospatialEngineeringBIM.sln
